### ISSUE TITLE
User-feedback messages on search syntax error

### ISSUE THREAD

**Issue by datazuul** [dbmdz/iiif-bookshelf-webapp#2]
currently Solr-Syntax-Exception is thrown and a error 500 is shown.
change to user message "Your search can not be executed. Please try a different search term."

**Comment by datazuul** [comment]
stacktrace:
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr/bookshelf: org.apache.solr.search.SyntaxError: Cannot parse '"""': Lexical error at line 1, column 4.  Encountered: <EOF> after : ""
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:575)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:241)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:230)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:150)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:943)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:958)
	at de.digitalcollections.iiif.bookshelf.backend.repository.impl.IiifManifestSummarySearchRepositoryImplSolrj.findBy(IiifManifestSummarySearchRepositoryImplSolrj.java:92)
	at de.digitalcollections.iiif.bookshelf.business.service.impl.IiifManifestSummaryServiceImpl.findAll(IiifManifestSummaryServiceImpl.java:58)
	at de.digitalcollections.iiif.bookshelf.frontend.controller.WebController.list(WebController.java:56)
