### ISSUE TITLE
import of manifests often fails (iiif api problems)

### ISSUE THREAD

**Issue by datazuul** [dbmdz/iiif-bookshelf-webapp#4]
when trying to import manifests parsing often fails (iiif api can not consume all instances of manifests). tested with importing manifest from stanford or yale (see https://github.com/ryanfb/iiif-universe/blob/gh-pages/iiif-universe.json). most manifests fail (not all). previously also manifest of older api versions were supported...

**Comment by datazuul** [comment]
example 1:

```
Could not read manifest from http://manifests.ydc2.yale.edu/manifest/DecretumMagistriGratiani
java.lang.ClassCastException: de.digitalcollections.iiif.model.GenericService cannot be cast to de.digitalcollections.iiif.model.image.ImageService
	at de.digitalcollections.iiif.bookshelf.business.impl.service.IiifManifestSummaryServiceImpl.lambda$getThumbnail$5(IiifManifestSummaryServiceImpl.java:196)
Caused by: java.lang.IllegalArgumentException: All annotations must **only** have ImageContent resources. Use otherContent for other types of content.
	at de.digitalcollections.iiif.model.sharedcanvas.Canvas.setImages(Canvas.java:64)
```

example 2:
```
Could not read manifest from http://manifests.ydc2.yale.edu/manifest/Admont23
java.lang.ClassCastException: de.digitalcollections.iiif.model.GenericService cannot be cast to de.digitalcollections.iiif.model.image.ImageService
```

example 3:
```
Could not read manifest from http://manifests.ydc2.yale.edu/manifest/MSPeniarth393DMultispectral
com.fasterxml.jackson.databind.JsonMappingException: All annotations must **only** have ImageContent resources. Use otherContent for other types of content.
 at [Source: (URL); line: 1, column: 4815] (through reference chain: de.digitalcollections.iiif.model.sharedcanvas.Manifest["sequences"]->java.util.ArrayList[0]->de.digitalcollections.iiif.model.sharedcanvas.Sequence["canvases"]->java.util.ArrayList[0]->de.digitalcollections.iiif.model.sharedcanvas.Canvas["images"])
```

**Comment by morpheus-87** [comment]
The manifests mentioned above are now working, but there are other failing examples now:

* http://manifests.desmm.yale.edu/manifest/CambridgeTrinityCollegeMSR_3_2

```
Manifest at uri http://manifests.desmm.yale.edu/manifest/CambridgeTrinityCollegeMSR_3_2 might be not standard conform, trying gracious parsing.
com.fasterxml.jackson.databind.JsonMappingException: class com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to class com.fasterxml.jackson.databind.node.ArrayNode (com.fasterxml.jackson.databind.node.ObjectNode and com.fasterxml.jackson.databind.node.ArrayNode are in unnamed module of loader 'app') (through reference chain: de.digitalcollections.iiif.model.sharedcanvas.Manifest["sequences"]->java.util.ArrayList[0]->de.digitalcollections.iiif.model.sharedcanvas.Sequence["canvases"]->java.util.ArrayList[2]->de.digitalcollections.iiif.model.sharedcanvas.Canvas["images"]->java.util.ArrayList[0]->de.digitalcollections.iiif.model.openannotation.Annotation["resource"])
```

* http://manifests.desmm.yale.edu/manifest/OxfordCorpusChristiMS198

```
Manifest at uri http://manifests.desmm.yale.edu/manifest/OxfordCorpusChristiMS198 might be not standard conform, trying gracious parsing.
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `de.digitalcollections.iiif.model.OtherContent`, problem: Illegal character in path at index 3: cf. Boydell & Brewer hardcopy catalogue
 at [Source: (org.apache.http.conn.EofSensorInputStream); line: 1, column: 452357] (through reference chain: de.digitalcollections.iiif.model.sharedcanvas.Manifest["related"]->java.lang.Object[0])
```

* http://manifests.desmm.yale.edu/manifest/OxfordCorpusChristiMS198Multispectral

```
Manifest at uri http://manifests.desmm.yale.edu/manifest/OxfordCorpusChristiMS198Multispectral might be not standard conform, trying gracious parsing.
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `de.digitalcollections.iiif.model.OtherContent`, problem: Illegal character in path at index 3: cf. Boydell & Brewer hardcopy catalogue
 at [Source: (org.apache.http.conn.EofSensorInputStream); line: 1, column: 322074] (through reference chain: de.digitalcollections.iiif.model.sharedcanvas.Manifest["related"]->java.lang.Object[0])
```

* http://manifests.desmm.yale.edu/manifest/BNFLatin3895

```
Manifest at uri http://manifests.desmm.yale.edu/manifest/BNFLatin3895 might be not standard conform, trying gracious parsing.
com.fasterxml.jackson.databind.JsonMappingException: class com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to class com.fasterxml.jackson.databind.node.ArrayNode (com.fasterxml.jackson.databind.node.ObjectNode and com.fasterxml.jackson.databind.node.ArrayNode are in unnamed module of loader 'app') (through reference chain: de.digitalcollections.iiif.model.sharedcanvas.Manifest["sequences"]->java.util.ArrayList[0]->de.digitalcollections.iiif.model.sharedcanvas.Sequence["canvases"]->java.util.ArrayList[327]->de.digitalcollections.iiif.model.sharedcanvas.Canvas["images"]->java.util.ArrayList[0]->de.digitalcollections.iiif.model.openannotation.Annotation["resource"])
```

* http://manifests.desmm.yale.edu/manifest/BlakeCopyL

```
Manifest at uri http://manifests.desmm.yale.edu/manifest/BlakeCopyL might be not standard conform, trying gracious parsing.
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `de.digitalcollections.iiif.model.sharedcanvas.Canvas`, problem: Illegal character in path at index 64: http://manifests.desmm.yale.edu/canvas/ba-obj-57619-0012-pub.tif  
 at [Source: (org.apache.http.conn.EofSensorInputStream); line: 1, column: 107697] (through reference chain: de.digitalcollections.iiif.model.sharedcanvas.Manifest["sequences"]->java.util.ArrayList[0]->de.digitalcollections.iiif.model.sharedcanvas.Sequence["canvases"]->java.util.ArrayList[120])
```

* http://manifests.desmm.yale.edu/manifest/B1992_8_11

```
Manifest at uri http://manifests.desmm.yale.edu/manifest/B1992_8_11 might be not standard conform, trying gracious parsing.
com.fasterxml.jackson.databind.JsonMappingException: Could not deserialize Resource. (through reference chain: de.digitalcollections.iiif.model.sharedcanvas.Manifest["sequences"]->java.util.ArrayList[0]->de.digitalcollections.iiif.model.sharedcanvas.Sequence["canvases"]->java.util.ArrayList[4]->de.digitalcollections.iiif.model.sharedcanvas.Canvas["images"]->java.util.ArrayList[0]->de.digitalcollections.iiif.model.openannotation.Annotation["on"])
```

* http://manifests.desmm.yale.edu/manifest/B1992_8_11

```
Could not read manifest from http://manifests.desmm.yale.edu/manifest/B1992_8_11 because of error class java.lang.String cannot be cast to class org.json.simple.JSONObject (java.lang.String is in module java.base of loader 'bootstrap'; org.json.simple.JSONObject is in unnamed module of loader 'app')
```

* https://digital.library.villanova.edu/Item/vudl:406578/Manifest

```
Manifest at uri https://digital.library.villanova.edu/Item/vudl:406578/Manifest might be not standard conform, trying gracious parsing.
com.fasterxml.jackson.databind.JsonMappingException: class java.util.ArrayList cannot be cast to class de.digitalcollections.iiif.model.sharedcanvas.Resource (java.util.ArrayList is in module java.base of loader 'bootstrap'; de.digitalcollections.iiif.model.sharedcanvas.Resource is in unnamed module of loader 'app') (through reference chain: de.digitalcollections.iiif.model.sharedcanvas.Manifest["within"]->java.util.ArrayList[0])
```

* https://digital.library.villanova.edu/Item/vudl:541878/Manifest

```
Manifest at uri https://digital.library.villanova.edu/Item/vudl:541878/Manifest might be not standard conform, trying gracious parsing.
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
```

**Comment by morpheus-87** [comment]
```
[2019-01-25 09:01:26,776  WARN] l.service.IiifManifestSummaryServiceImpl:  68 [http-nio-8080-exec-10] - Manifest at uri http://manifests.desmm.yale.edu/manifest/CambridgeTrinityCollegeMSR_3_2 might be not standard conform, trying gracious parsing.
com.fasterxml.jackson.databind.JsonMappingException: class com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to class com.fasterxml.jackson.databind.node.ArrayNode (com.fasterxml.jackson.databind.node.ObjectNode and com.fasterxml.jackson.databind.node.ArrayNode are in unnamed module of loader 'app') (through reference chain: de.digitalcollections.iiif.model.sharedcanvas.Manifest["sequences"]->java.util.ArrayList[0]->de.digitalcollections.iiif.model.sharedcanvas.Sequence["canvases"]->java.util.ArrayList[2]->de.digitalcollections.iiif.model.sharedcanvas.Canvas["images"]->java.util.ArrayList[0]->de.digitalcollections.iiif.model.openannotation.Annotation["resource"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1711)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:254)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:441)
...
Caused by: java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to class com.fasterxml.jackson.databind.node.ArrayNode (com.fasterxml.jackson.databind.node.ObjectNode and com.fasterxml.jackson.databind.node.ArrayNode are in unnamed module of loader 'app')
	at de.digitalcollections.iiif.model.jackson.serialization.ResourceDeserializer.parseChoice(ResourceDeserializer.java:92)
	at de.digitalcollections.iiif.model.jackson.serialization.ResourceDeserializer.deserialize(ResourceDeserializer.java:60)
	at de.digitalcollections.iiif.model.jackson.serialization.ResourceDeserializer.deserialize(ResourceDeserializer.java:36)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:252)
```
